site_name: COEX RaceMini
theme:
  name: material
plugins:
  - search:
      lang:
        - en
        - ru
markdown_extensions:
  - attr_list


extra_css:
    - css/extra.css

nav:
    - 'Сборка гоночного дрона COEX Race Mini' : assembly_index.md
    - 'Варианты сборки':
        - 'Комплектующие iflight': assembly_iflight.md
        - 'Комплектующие mamba': assembly_mamba.md
    - 'Настройка пульта' : rc.md
    - 'Настройка полетного контроллера' : setup.md
    - '3D-печать рамы' : 3d_print.md
